SELECT @@SERVERNAME
CREATE DATABASE SEMINAR2
USE SEMINAR2

USE SHOP

CREATE TABLE Ships
(
	ShipID INT PRIMARY KEY,
	SNAME VARCHAR(100))

CREATE TABLE Pirates
(
	PiratesID INT PRIMARY KEY,
	PName VARCHAR(100),
	ShipID INT REFERENCES Ships(ShipID))

INSERT Ships VALUES (1,'s1'),(2,'s2')

INSERT Pirates VALUES (1,'p1',1),(2,'p2',1),(3,'p3',2)

SELECT * FROM Ships
SELECT * FROM Pirates